package org.ouobpo.study.bpstudy200808.drools

import org.ouobpo.study.bpstudy200808.drools.Employee

rule "RuleA"
	when
		emp : Employee(age > 30)
	then
		System.out.println("RuleA> " + emp);
end

rule "RuleB"
	when
		emp : Employee(employeeNo == "ABC003")
	then
		System.out.println("RuleB> " + emp);
end

rule "RuleC"
	when
		emp : Employee(name == "佐藤")
	then
		System.out.println("RuleC> " + emp);
end